spring:

 server:
    port: 8085
    
 datasource:
   url: jdbc:mysql://localhost:3306/sakuradb
   username: root
   password: shya2402
   driver-class-name: com.mysql.jdbc.Driver

 jpa:
   show-sql: true
   hibernate:
     ddl-auto: update
     
